import type {Metadata} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import {CabecalhoPagina} from "@/components/CabecalhoPagina";
import {SeloSituacao} from "@/components/SeloSituacao";
import {formatarMoeda,formatarValorRegistro} from "@/lib/formato";
import {criarClienteServidor,exigirSessao} from "@/lib/supabase/server";import {ConfirmarUnificacao} from "../ConfirmarUnificacao";
export const metadata:Metadata={title:"Cliente"};
export default async function Cliente(props:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){const sessao=await exigirSessao();const {id:raw}=await props.params;const query=await props.searchParams;const unificar=Number(typeof query.unificar==="string"?query.unificar:"");const id=Number(raw);if(!Number.isSafeInteger(id)||id<1)notFound();const db=await criarClienteServidor();const [{data:c},{data:regs},{data:notas}]=await Promise.all([db.from("vw_clientes").select("*").eq("id",id).maybeSingle(),db.from("vw_registros").select("num,ano,escopo,situacao,tipo,valor").eq("cliente_id",id).order("ano",{ascending:false}),db.from("vw_notas").select("id,numero,data_emissao,valor,titulo").eq("cliente_id",id).order("data_emissao",{ascending:false})]);if(!c)notFound();const {data:origem}=sessao.papel==="admin"&&Number.isSafeInteger(unificar)&&unificar>0&&unificar!==id?await db.from("clientes").select("id,nome").eq("id",unificar).maybeSingle():{data:null};return <><CabecalhoPagina sobre={<Link href="/clientes">Clientes</Link>} titulo={c.nome} descricao={c.propostas+" propostas · "+c.contratos+" contratos · faturado "+formatarMoeda(Number(c.faturado))}/>{typeof query.unificado==="string"?<p className="aviso aviso-sucesso">Clientes unificados; os registros foram movidos e o nome de origem ficou preservado.</p>:null}{query.erro==="unificar"?<p className="aviso aviso-erro">Não foi possível unificar. Verifique se ambos os clientes ainda existem.</p>:null}{origem?<ConfirmarUnificacao origem={origem.id} nomeOrigem={origem.nome} destino={id} nomeDestino={c.nome}/>:null}<section className="painel"><div className="painel-cabecalho"><h2>Propostas e contratos</h2></div><div className="tabela-rolagem"><table className="tabela"><thead><tr><th>Nº / ano</th><th>Escopo</th><th>Situação</th><th className="num">Valor</th></tr></thead><tbody>{(regs??[]).map(x=><tr key={x.num}><td><Link href={"/registros/"+x.num}>{x.num} · {x.ano}</Link></td><td>{x.escopo}</td><td><SeloSituacao situacao={x.situacao}/></td><td className="num">{x.valor===null?"—":formatarValorRegistro(Number(x.valor),x.tipo)}</td></tr>)}</tbody></table></div></section><section className="painel" style={{marginTop:16}}><div className="painel-cabecalho"><h2>Notas fiscais</h2></div><div className="tabela-rolagem"><table className="tabela"><thead><tr><th>NF</th><th>Emissão</th><th>Título</th><th className="num">Valor</th></tr></thead><tbody>{(notas??[]).map(n=><tr key={n.id}><td>{n.numero||"s/nº"}</td><td>{n.data_emissao||"—"}</td><td>{n.titulo}</td><td className="num">{formatarMoeda(Number(n.valor))}</td></tr>)}</tbody></table></div></section></>;}
